name: Cell Restonator

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  peaklist-analyzer-test:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python --version
          pip install -r requirements.txt
      - name: Black --check
        run: |
          pip install black
          black --check src
          black --check tests
      - name: Test with pytest
        run: |
          pip install pytest==6.2.5
          pip install pytest-env==0.6.2
          pytest tests
